# Generated by Django 3.2.7 on 2021-09-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartamentos', '0002_apartamento_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartamento',
            name='apartamento_publicado',
            field=models.BooleanField(default=False),
        ),
    ]
