# Generated by Django 3.2.7 on 2021-09-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartamentos', '0003_apartamento_apartamento_publicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartamento',
            name='foto_apartamento',
            field=models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/'),
        ),
    ]
