# Generated by Django 3.2.7 on 2021-09-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartamentos', '0004_apartamento_foto_apartamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartamento',
            name='foto_apartamento',
            field=models.ImageField(blank=True, upload_to='C:/Users/rafae/Documents/PI/media/fotos/%d/%m/%Y/'),
        ),
    ]
